# Generated by Django 3.1.4 on 2021-01-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='amazon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='hulu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='netflix',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='amazon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='hulu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='netflix',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='youtube',
            field=models.IntegerField(default=0),
        ),
    ]
